/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2MFg6zlSB3i
 */
import "./../app/globals.css";
import Image from "next/image"
import Link from "next/link"
import { JSX, SVGProps } from "react";

export default function CookiesPolicy() {
  const fullYear: number = new Date().getFullYear()

  return (
    <div key="1" className="flex flex-col min-h-screen bg-white dark:bg-gray-900 animate-fade-in-up">
      <header className="px-4 lg:px-6 h-16 animate-slide-in-down">
        <Link className="flex items-center justify-center" href="/">
          <Image alt="TamoTam logo"
            src="/logo.svg" height={102} width={394} />
          <span className="sr-only">TamoTam</span>
        </Link>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 animate-fade-in-up">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight text-center">Cookies Policy</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-justify">Effective Date: 20.02.2024</p>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-justify">
                Thank you for visiting the TamoTam website. This Cookies Policy explains how we use cookies and similar tracking technologies on our website (&quot;Site&quot;). By using our Site, you consent to the use of cookies as described in this policy.
              </p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">What Are Cookies?</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>Cookies are small text files that are stored on your device when you visit a website. They contain information about your browsing activity on the website and help enhance your experience by enabling certain features and functionalities.
              </p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Types of Cookies We Use</h3>
              <ol className="list-decimal list-inside text-justify" style={{ width: 600 }}>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Essential Cookies</strong>: These cookies are necessary for the operation of our Site. They enable basic functions such as page navigation and access to secure areas of the website. Without these cookies, the Site may not function properly.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Performance Cookies</strong>: These cookies collect information about how visitors use our Site, such as which pages they visit most frequently and if they encounter any errors. This data helps us improve the performance and usability of the Site.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Functionality Cookies</strong>: These cookies enable the Site to remember choices you make (such as language or region) and provide enhanced features and personalized content based on your preferences.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Analytics Cookies</strong>: We use analytics cookies to gather information about traffic to our Site and analyze how visitors interact with our content. This helps us understand user behavior and improve the relevance and effectiveness of our marketing efforts.
                </li>
              </ol>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Third-Party Cookies</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>We may also use third-party cookies, such as those provided by Google Analytics, to track and analyze usage data on our Site. These cookies are governed by the respective privacy policies of the third-party providers and are not controlled by us.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Managing Cookies</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>You can control and/or delete cookies as you wish. Most web browsers allow you to manage your cookie preferences through the browser settings. However, please note that disabling certain cookies may affect the functionality of the Site and your ability to access certain features.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Updates to This Cookies Policy</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>We reserve the right to update this Cookies Policy from time to time to reflect changes in our practices or legal requirements. We will notify you of any material changes by posting the updated policy on our website.
              </p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Contact Us</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>If you have any questions, concerns, or feedback regarding this Cookies Policy, please contact us at <a aria-label='contact@tamotam.com. Click here to send us an e-mail.' className="hover:underline underline-offset-4" href='mailto:contact@tamotam.com?subject=Mail from tamotam.com&body=Hi TamoTam!%0D%0A%0D%0AMy mail is about:%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0ABest regards,%0D%0A' title='contact@tamotam.com'>contact@tamotam.com</a>.</p>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>By continuing to use our Site, you acknowledge that you have read, understood, and agree to be bound by this Cookies Policy.</p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 md:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t animate-slide-in-up">
        <p className="text-xs text-gray-500 dark:text-gray-400">© {fullYear} TamoTam. All rights reserved.</p>
        <nav className="md:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="/cookies-policy">
            Cookies Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="/privacy-policy">
            Privacy Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="/terms-conditions">
            Terms & Conditions
          </Link>
        </nav>
        <div className="flex gap-4 sm:gap-6 md:ml-auto">
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.linkedin.com/company/tamotam">
            <LinkedinIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://discord.gg/b4KaGu4z">
            <DiscIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://twitter.com/TamoTamApp">
            <XIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.instagram.com/tamotamapp">
            <InstagramIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://github.com/tamotam-com">
            <GithubIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.tiktok.com/@tamotamapp">
            <YoutubeIcon className="h-6 w-6" />
          </Link>
        </div>
      </footer>
    </div>
  )
}


function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function DiscIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}


function InstagramIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function YoutubeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}
