/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WCFrNeMBc7u
 */
import Image from "next/image"
import Link from "next/link"
import { JSX, SVGProps } from "react"

export default function Home() {
  const fullYear: number = new Date().getFullYear()

  return (
    <div key="1" className="flex flex-col min-h-screen bg-white dark:bg-gray-900 animate-fade-in-up">
      <header className="px-4 lg:px-6 h-16 animate-slide-in-down">
        <Link className="flex items-center justify-center" href="/">
          <Image alt="TamoTam logo"
            src="/logo.svg" height={102} width={394} />
          <span className="sr-only">TamoTam</span>
        </Link>
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 border-b animate-fade-in-up">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto px-4 sm:px-6 md:px-10 md:grid-cols-2">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem] pt-12 md:pt-24 lg:pt-36 text-center animate-accordion-up">
                  🤙 TamoTam. HangOut. Offline.
                </h1>
                <br />
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400 text-center text-xl pb-6">
                  Prioritize real-world connections.
                  <br />
                  In a Real, Offline, Social Life.
                </p>
              </div>
              <div className="flex flex-col items-start space-y-4 pb-8 md:pb-12 lg:pb-16">
                <img
                  alt="Social Life Improvement"
                  className="mx-auto aspect-[1/1] overflow-hidden rounded-xl object-cover"
                  src="/image.webp"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-4 md:py-8 lg:py-12 animate-fade-in-up">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Go Online to be Offline.</h2>
                <p className="text-gray-500 dark:text-gray-400">
                  Nowadays, online and offline worlds must exist together; consider using them smartly.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-1 md:gap-12 lg:grid-cols-3">
              <div className="grid gap-1 text-center">
                <HeartIcon className="h-12 w-12 mx-auto" />
                <h3 className="text-lg font-bold">Digital Wellbeing</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 sm:text-center lg:text-justify">
                  Spending more time offline and fostering face-to-face interactions is vital for improving digital wellbeing.
                </p>
              </div>
              <div className="grid gap-1 text-center">
                <ScaleIcon className="h-12 w-12 mx-auto" />
                <h3 className="text-lg font-bold">Balance</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 sm:text-center lg:text-justify">
                  Investing time in meaningful interactions with others and engaging in offline activities can lead to a more fulfilling and balanced lifestyle.
                </p>
              </div>
              <div className="grid gap-1 text-center" style={{ marginBottom: 20 }}>
                <FileWarningIcon className="h-12 w-12 mx-auto" />
                <h3 className="text-lg font-bold">Misinformation</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 sm:text-center lg:text-justify">
                  Curated content can distort reality, fueling envy and low self-esteem. Make sure to be away from the trap of toxic content.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-10 md:py-12 lg:py-16 bg-gray-100 dark:bg-gray-800 animate-fade-in-up">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight text-center">
                Social applications have revolutionized the Homo Sapiens.
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-justify py-6 md:py-8 lg:py-10">
                Once praised for fostering connectivity, social applications now raise concerns about their negative impacts, causing us to speak less and less with each other.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl text-justify">
                “While technology offers numerous benefits, excessive screen time can lead to various negative consequences. Studies link social media use to anxiety, depression, and poses a threat to societal trust and democracy.“
              </blockquote>
              <div>
                <div className="font-semibold">ChatGPT Plus</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">Model GPT-4</div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 animate-fade-in-up">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight text-center">Say No to Addictive Social Media.</h2>

              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-center">
                Leading to time social isolation, decreased productivity, and mental health issues.
              </p>
            </div>
            <div className="flex justify-center space-x-4">
              <Link
                className="inline-flex h-12 items-center justify-center rounded-md bg-[#0A5CFF] px-10 text-base font-medium text-white shadow transition-colors hover:bg-[#0A5CFF]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#0A5CFF] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#0A5CFF] dark:text-white dark:hover:bg-[#0A5CFF]/90 dark:focus-visible:ring-[#0A5CFF]"
                href="https://apps.apple.com/pl/app/tamotam-hangout-offline/id1625649957"
                rel="noopener"
                target="_blank"
              >
                <AppleIcon className="h-6 w-6 mr-2" />
                Download on App Store
              </Link>
              <Link
                className="inline-flex h-12 items-center justify-center rounded-md bg-[#3C79E6] px-10 text-base font-medium text-white shadow transition-colors hover:bg-[#3C79E6]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#3C79E6] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#3C79E6] dark:text-white dark:hover:bg-[#3C79E6]/90 dark:focus-visible:ring-[#3C79E6]"
                href="https://play.google.com/store/apps/details?id=com.tamotam.application"
                rel="noopener"
                target="_blank"
              >
                <PlayIcon className="h-6 w-6 mr-2" />
                Get it on Google Play
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 md:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t animate-slide-in-up">
        <p className="text-xs text-gray-500 dark:text-gray-400">© {fullYear} TamoTam. All rights reserved.</p>
        <nav className="md:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="/cookies-policy">
            Cookies Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="/privacy-policy">
            Privacy Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="/terms-conditions">
            Terms & Conditions
          </Link>
        </nav>
        <div className="flex gap-4 sm:gap-6 md:ml-auto">
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.linkedin.com/company/tamotam" rel="noopener"
            target="_blank">
            <LinkedinIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://discord.gg/b4KaGu4z" rel="noopener"
            target="_blank">
            <DiscIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://twitter.com/TamoTamApp" rel="noopener"
            target="_blank">
            <TwitterIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.instagram.com/tamotamapp" rel="noopener"
            target="_blank">
            <InstagramIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://github.com/tamotam-com" rel="noopener"
            target="_blank">
            <GithubIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.tiktok.com/@tamotamapp" rel="noopener"
            target="_blank">
            <YoutubeIcon className="h-6 w-6" />
          </Link>
        </div>
      </footer>
    </div>
  )
}


function HeartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function ScaleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z" />
      <path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z" />
      <path d="M7 21h10" />
      <path d="M12 3v18" />
      <path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2" />
    </svg>
  )
}


function FileWarningIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <path d="M12 9v4" />
      <path d="M12 17h.01" />
    </svg>
  )
}


function AppleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function PlayIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="5 3 19 12 5 21 5 3" />
    </svg>
  )
}


function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function DiscIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}


function TwitterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function InstagramIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function YoutubeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}
