/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2MFg6zlSB3i
 */
import "./../app/globals.css";
import Image from "next/image"
import Link from "next/link"
import { JSX, SVGProps } from "react";

export default function PrivacyPolicy() {
  const fullYear: number = new Date().getFullYear()

  return (
    <div key="1" className="flex flex-col min-h-screen bg-white dark:bg-gray-900 animate-fade-in-up">
      <header className="px-4 lg:px-6 h-16 animate-slide-in-down">
        <Link className="flex items-center justify-center" href="/">
          <Image alt="TamoTam logo"
            src="/logo.svg" height={102} width={394} />
          <span className="sr-only">TamoTam</span>
        </Link>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 animate-fade-in-up">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight text-center">Privacy Policy</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-justify">
                Thank you for using TamoTam, a mobile application developed by IBStructure Daniel Danielecki. This Privacy Policy outlines how we collect, use, and protect your personal information when you use our mobile application (&quot;App&quot;).
              </p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Information We Collect</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>We may collect various types of information when you use TamoTam, including:
              </p>
              <ol className="list-decimal list-inside text-justify" style={{ width: 600 }}>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Personal Information</strong>: This may include your name, email address, phone number, and other identifiers you provide when creating an account or contacting us for support.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Device Information</strong>: We may collect information about your device, such as its unique device identifier, IP address, operating system version, and mobile network information.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Usage Information</strong>: We gather data on how you interact with our App, including the features you use, the content you view, and the frequency and duration of your interactions.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Location Information</strong>: With your consent, we may collect your precise or approximate location data to provide location-based services within the App.</li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Photos and Camera Access</strong>: We may request access to your device&apos;s camera and photo library to enable you to upload and share photos within the App.</li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Logs for Analytics</strong>: We collect logs and analytics data to understand how our App is used, analyze trends, and improve the user experience.</li>
              </ol>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">How We Use Your Information</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>We use the information we collect for the following purposes:</p>
              <ol className="list-decimal list-inside text-justify" style={{ width: 600 }}>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Providing and Improving Our Services</strong>: We use your information to deliver the features and functionalities of the App, optimize user experience, and develop new features.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Localization</strong>: We may use your location data to provide localized content and services tailored to your geographic region.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Personalization</strong>: We personalize your experience within the App by providing content and recommendations tailored to your preferences and usage patterns.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Communication</strong>: We may use your contact information to communicate with you about updates, promotions, or important notices related to the App.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Analytics</strong>: We analyze user behavior and trends to understand how our App is used, identify areas for improvement, and measure the effectiveness of our marketing efforts.
                </li>
              </ol>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Data Sharing and Disclosure</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>We may share your information with third parties under the following circumstances:</p>
              <ol className="list-decimal list-inside text-justify" style={{ width: 600 }}>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Service Providers</strong>: We may engage third-party service providers to assist us in operating the App, processing payments, or analyzing user data. These service providers are obligated to protect your information and are prohibited from using it for any other purpose.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Legal Compliance</strong>: We may disclose your information if required by law, regulation, or legal process, or if we believe such action is necessary to protect the rights, property, or safety of our users or others.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Business Transfers</strong>: In the event of a merger, acquisition, or sale of all or a portion of our assets, your information may be transferred as part of the transaction. We will notify you via email or prominent notice on our website if such a transfer occurs and inform you of any changes to our Privacy Policy.
                </li>
              </ol>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Data Security</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>We take reasonable measures to safeguard your information against unauthorized access, disclosure, alteration, or destruction. However, please be aware that no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee absolute security.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Your Choices</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>You can manage your communication preferences and opt-out of certain data collection and processing by adjusting your settings within the App. However, please note that opting out may affect your ability to access certain features or functionalities.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Children&apos;s Privacy</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>TamoTam is not intended for use by children under the age of 13. We do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected information from a child under 13, please contact us immediately, and we will take steps to delete such information.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Updates to This Privacy Policy</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. We will notify you of any material changes by posting the updated Privacy Policy on our website or through other means.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Contact Us</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>If you have any questions, concerns, or feedback regarding this Privacy Policy or our data practices, please contact us at <a aria-label='contact@tamotam.com. Click here to send us an e-mail.' className="hover:underline underline-offset-4" href='mailto:contact@tamotam.com?subject=Mail from tamotam.com&body=Hi TamoTam!%0D%0A%0D%0AMy mail is about:%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0ABest regards,%0D%0A' title='contact@tamotam.com'>contact@tamotam.com</a>.</p>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>By using TamoTam, you consent to the collection and use of your information as outlined in this Privacy Policy.</p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t animate-slide-in-up">
        <p className="text-xs text-gray-500 dark:text-gray-400">© {fullYear} TamoTam. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="/cookies-policy">
            Cookies Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="/privacy-policy">
            Privacy Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="/terms-conditions">
            Terms & Conditions
          </Link>
        </nav>
        <div className="flex gap-4 sm:gap-6 ml-auto">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <LinkedinIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <DiscIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <XIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <InstagramIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <GithubIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <YoutubeIcon className="h-6 w-6" />
          </Link>
        </div>
      </footer>
    </div>
  )
}


function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function DiscIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}


function InstagramIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function YoutubeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}
