/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2MFg6zlSB3i
 */
import "./../app/globals.css";
import Image from "next/image"
import Link from "next/link"
import { JSX, SVGProps } from "react";

export default function TermsConditions() {
  const fullYear: number = new Date().getFullYear()

  return (
    <div key="1" className="flex flex-col min-h-screen bg-white dark:bg-gray-900 animate-fade-in-up">
      <header className="px-4 lg:px-6 h-16 animate-slide-in-down">
        <Link className="flex items-center justify-center" href="/">
          <Image alt="TamoTam logo"
            src="/logo.svg" height={102} width={394} />
          <span className="sr-only">TamoTam</span>
        </Link>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 animate-fade-in-up">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight text-center">Terms & Conditions</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-justify">Effective Date: 20.02.2024</p>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-justify">
                Thank you for choosing TamoTam, a mobile application developed by IBStructure Daniel Danielecki. By downloading, accessing, or using the TamoTam mobile application (&quot;App&quot;), you agree to be bound by these Terms & Conditions. Please read these Terms carefully before using the App.
              </p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Acceptance of Terms</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>By using the TamoTam App, you agree to comply with and be bound by these Terms & Conditions, as well as any additional terms and policies referenced herein. If you do not agree to these Terms, please do not use the App.
              </p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">License and Restrictions</h3>
              <ol className="list-decimal list-inside text-justify" style={{ width: 600 }}>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>License</strong>: Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to use the App for your personal, non-commercial use.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Restrictions</strong>: You may not modify, reverse engineer, decompile, disassemble, or attempt to derive the source code of the App. You may not distribute, sublicense, lease, rent, or transfer the App or any of its components to any third party.
                </li>
              </ol>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">User Accounts</h3>
              <ol className="list-decimal list-inside text-justify" style={{ width: 600 }}>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Account Creation</strong>: In order to access certain features of the App, you may be required to create an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Account Security</strong>: You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account or any other breach of security.
                </li>
              </ol>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">User Content</h3>

              <ol className="list-decimal list-inside text-justify" style={{ width: 600 }}>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Ownership</strong>: You retain ownership of any content you upload, post, or submit to the App (&quot;User Content&quot;). By submitting User Content, you grant us a non-exclusive, royalty-free, worldwide, perpetual, irrevocable license to use, reproduce, modify, adapt, publish, translate, distribute, and display such User Content in connection with the operation and promotion of the App.
                </li>
                <li className="text-gray-500 dark:text-gray-400">
                  <strong>Prohibited Content</strong>: You agree not to submit any User Content that is unlawful, harmful, threatening, abusive, harassing, defamatory, obscene, vulgar, or otherwise objectionable.
                </li>
              </ol>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Intellectual Property</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>The App and its contents, including but not limited to text, graphics, logos, images, and software, are protected by copyright, trademark, and other intellectual property laws. You may not copy, reproduce, modify, distribute, or create derivative works based on the App or any of its contents without our prior written consent.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Privacy</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>Our collection and use of your personal information are governed by our <Link className="hover:underline underline-offset-4" href="/privacy-policy">
                Privacy Policy
              </Link> By using the App, you consent to the collection and use of your information as outlined in the Privacy Policy.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Disclaimers</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>THE APP IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DISCLAIM ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

              </p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Limitation of Liability</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>IN NO EVENT SHALL WE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE APP, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Indemnification</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>You agree to indemnify, defend, and hold harmless [Your Company Name] and its affiliates, officers, directors, employees, agents, and licensors from and against any and all claims, liabilities, damages, losses, costs, or expenses arising out of or in connection with your use of the App or your violation of these Terms.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Governing Law</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>These Terms & Conditions shall be governed by and construed in accordance with the laws of Poland, without regard to its conflict of law provisions.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Changes to Terms & Conditions</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>We reserve the right to modify or update these Terms & Conditions at any time. You are responsible for regularly reviewing these Terms for changes. Your continued use of the App following the posting of any changes constitutes acceptance of those changes.</p>
              <h3 className="text-2xl font-bold tracking-tighter md:text-3xl/tight text-center">Contact Us</h3>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>If you have any questions, concerns, or feedback regarding these Terms & Conditions, please contact us at <a aria-label='contact@tamotam.com. Click here to send us an e-mail.' className="hover:underline underline-offset-4" href='mailto:contact@tamotam.com?subject=Mail from tamotam.com&body=Hi TamoTam!%0D%0A%0D%0AMy mail is about:%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0ABest regards,%0D%0A' title='contact@tamotam.com'>contact@tamotam.com</a>.</p>
              <p className="text-justify text-gray-500 dark:text-gray-400" style={{ width: 600 }}>By using the TamoTam App, you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions.</p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 md:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t animate-slide-in-up">
        <p className="text-xs text-gray-500 dark:text-gray-400">© {fullYear} TamoTam. All rights reserved.</p>
        <nav className="md:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="/cookies-policy">
            Cookies Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="/privacy-policy">
            Privacy Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="/terms-conditions">
            Terms & Conditions
          </Link>
        </nav>
        <div className="flex gap-4 sm:gap-6 md:ml-auto">
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.linkedin.com/company/tamotam">
            <LinkedinIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://discord.gg/b4KaGu4z">
            <DiscIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://twitter.com/TamoTamApp">
            <XIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.instagram.com/tamotamapp">
            <InstagramIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://github.com/tamotam-com">
            <GithubIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="https://www.tiktok.com/@tamotamapp">
            <YoutubeIcon className="h-6 w-6" />
          </Link>
        </div>
      </footer>
    </div>
  )
}


function LinkedinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function DiscIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}


function InstagramIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function YoutubeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}
