/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WCFrNeMBc7u
 */
import Link from "next/link"

export function Component() {
  return (
    <div key="1" className="flex flex-col min-h-screen bg-white dark:bg-gray-900 animate-fade-in-up">
      <header className="px-4 lg:px-6 h-16 flex items-center justify-between animate-slide-in-down">
        <Link className="flex items-center justify-center" href="#">
          <SmartphoneIcon className="h-6 w-6" />
          <span className="sr-only">Mobile App</span>
        </Link>
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 border-y animate-fade-in-up">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Improve Your Social Life with Our App
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Our app is designed to improve your social life by encouraging less screen time and more real-world
                  interactions. Start your journey towards a healthier digital lifestyle today.
                </p>
                <div className="space-x-4">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="#"
                  >
                    Get Started
                  </Link>
                </div>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <img
                  alt="Social Life Improvement"
                  className="mx-auto aspect-[1/1] overflow-hidden rounded-xl object-cover"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 animate-fade-in-up">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Key Features
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Why Choose Our App</h2>
                <p className="text-gray-500 dark:text-gray-400">
                  Our app encourages people to spend time off screen, promoting a healthier digital lifestyle and
                  improving social life.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <FastForwardIcon className="h-6 w-6" />
                <h3 className="text-lg font-bold">Speed</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Our app is built for speed. Enjoy lightning-fast performance and responsiveness.
                </p>
              </div>
              <div className="grid gap-1">
                <LockIcon className="h-6 w-6" />
                <h3 className="text-lg font-bold">Security</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  We prioritize your security. Your data is safe and secure with us.
                </p>
              </div>
              <div className="grid gap-1">
                <UserIcon className="h-6 w-6" />
                <h3 className="text-lg font-bold">Social Life Improvement</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Our app is designed to improve your social life by encouraging less screen time and more real-world
                  interactions.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800 animate-fade-in-up">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                The Impact of Social Apps on Health
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                While social apps can be a great way to stay connected, it's important to be aware of their potential
                impact on mental and physical health. Excessive use can lead to issues like anxiety, depression, and
                sleep disorders.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                “I've noticed a significant improvement in my mental health since I started using this app. It's
                designed to promote healthy usage habits, and it really shows.“
              </blockquote>
              <div>
                <div className="font-semibold">Jane Doe</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">App User</div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 animate-fade-in-up">
          <div className="container grid items-center justify-center gap-4 px-4 md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Download Our App</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Get started with our app today. Available on iOS and Android.
              </p>
            </div>
            <div className="flex justify-center space-x-4">
              <Link
                className="inline-flex h-12 items-center justify-center rounded-md bg-[#0A5CFF] px-10 text-base font-medium text-white shadow transition-colors hover:bg-[#0A5CFF]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#0A5CFF] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#0A5CFF] dark:text-white dark:hover:bg-[#0A5CFF]/90 dark:focus-visible:ring-[#0A5CFF]"
                href="#"
              >
                <AppleIcon className="h-6 w-6 mr-2" />
                Download on App Store
              </Link>
              <Link
                className="inline-flex h-12 items-center justify-center rounded-md bg-[#3C79E6] px-10 text-base font-medium text-white shadow transition-colors hover:bg-[#3C79E6]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#3C79E6] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#3C79E6] dark:text-white dark:hover:bg-[#3C79E6]/90 dark:focus-visible:ring-[#3C79E6]"
                href="#"
              >
                <PlayIcon className="h-6 w-6 mr-2" />
                Get it on Google Play
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t animate-slide-in-up">
        <p className="text-xs text-gray-500 dark:text-gray-400">© Mobile App. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
        <div className="flex gap-4 sm:gap-6 ml-auto">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <LinkedinIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <DiscIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <TwitterIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <InstagramIcon className="h-6 w-6" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <GithubIcon className="h-6 w-6" />
          </Link>
        </div>
      </footer>
    </div>
  )
}


function SmartphoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}


function FastForwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="13 19 22 12 13 5 13 19" />
      <polygon points="2 19 11 12 2 5 2 19" />
    </svg>
  )
}


function LockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function AppleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="5 3 19 12 5 21 5 3" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function DiscIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}
